- name: install nginx apt key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu trusty nginx' state=present

- name: install nginx
  apt: name=nginx update_cache=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes   