- name: Install prerequisites
  apt: name=python-software-properties state=present

- name: add python repository
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7' state=present

- name: install python
  apt: name=python2.7 update_cache=yes only_upgrade=yes
