- name: remove old python
  apt: name=python force=yes purge=yes state=absent

- name: Install prerequisites
  apt: name=python-software-properties

- name: add python repository
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7' 

- name: install python
  apt: name=python2.7 update_cache=yes state=latest
