- name: install mongo apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0C49F3730359A14518585931BC711F9BA15703C6

- name: add mongo repository
  apt_repository: repo='deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse' state=present

- name: install mongodb-org
  apt: name=mongodb-org update_cache=yes

- name: copy mongo conf file
  template: src=templates/mongo.conf.j2 dest=/etc/mongod.conf owner=root group=root mode=0644

- name: run mongod
  service: name=mongod state=restarted enabled=yes  