- name: install mongo apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927

- name: add mongo repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: install mongodb-org
  apt: name=mongodb-org update_cache=yes  