# file: build-essential/tasks/main.yml

- name: Read the family variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Make sure the packages are installed (Debian)
  become: yes
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{buildessential_packages}}"
  register: output
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove' not in output.stdout and 'not upgraded' not in output.stdout"
  when: ansible_os_family == "Debian"

- name: install python-virtualenv 
  apt: name=python-virtualenv 
  when: ansible_os_family == "Debian"

- name: install python-dev
  apt: name=python-dev
  when: ansible_os_family == "Debian"

- name: install libffi-dev
  apt: name=libffi-dev
  when: ansible_os_family == "Debian"

- name: install libssl-dev
  apt: name=libssl-dev
  when: ansible_os_family == "Debian"

- name: install pip
  easy_install: name=pip
  when: ansible_os_family == "Debian"   


