# file: build-essential/tasks/main.yml

- name: Read the family variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Make sure the packages are installed (Debian)
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items: "{{buildessential_packages}}"
  register: output
  when: ansible_os_family == "Debian"
  
