- name: Set node version
  set_fact:
    node_version: 6.9.5
- name: set node version
  shell: ". /home/{{username_on_the_host}}/.nvm/nvm.sh && nvm alias default node {{node_version}}"
  become: no
  become_user: '{{username_on_the_host}}'
- file:
    src: '/home/{{username_on_the_host}}/.nvm/versions/node/v{{node_version}}/bin/node'
    dest: '/usr/local/bin/node'        
    force: yes
    mode: 0777    
    state: link
- file:
    src: '/home/{{username_on_the_host}}/.nvm/versions/node/v{{node_version}}/bin/npm'
    dest: '/usr/local/bin/npm'        
    force: yes
    mode: 0777    
    state: link  
- file: path=/opt/ state=directory mode=0755 owner='{{username_on_the_host}}'
- name: Install git
  apt: name=git update_cache=yes 

- name: Install hoardd from GitHub
  git: "repo=https://github.com/marcusdb/hoardd dest=/opt/hoardd update=yes "
  become_user: '{{username_on_the_host}}'

- name: NPM Install hoardd
  npm: path=/opt/hoardd
  become_user: '{{username_on_the_host}}'

- name: Configure hoardd
  template: src=files/hoardd/config.json.j2 dest=/opt/hoardd/config.json '{{username_on_the_host}}' mode=0644
  become_user: '{{username_on_the_host}}'

- name: copy hoardd carbon configuration
  copy: >
    src=files/supervisor/hoardd.conf
    dest=/etc/supervisor/conf.d/hoardd.conf
    owner=root
    group=root
    mode=0644

- name: run supervisor
  service: name=supervisor state=restarted enabled=yes  


