- file: path=/opt/ state=directory mode=0755 owner='{{username_on_the_host}}'

- name: Install git
  apt: name=git update_cache=yes 

- name: Install hoardd from GitHub
  git: "repo=https://github.com/marcusdb/hoardd dest=/opt/hoardd update=yes "
  become_user: '{{username_on_the_host}}'

- name: NPM Install hoardd
  npm: path=/opt/hoardd
  become_user: '{{username_on_the_host}}'

- name: Configure hoardd
  template: src=files/hoardd/config.json.j2 dest=/opt/hoardd/config.json '{{username_on_the_host}}' mode=0644
  become_user: '{{username_on_the_host}}'

- name: copy systemd config
  template: src=files/hoardd.service dest=/etc/systemd/system/hoardd.service mode=0755
  
- name: start hoardd service
  service: name="hoardd" state=restarted enabled=yes 


