- name: install elasticsearch apt key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: add elasticsearch repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present

- name: install apt-transport-https
  apt: name=apt-transport-https state=latest update_cache=yes

- name: install elasticsearch
  apt: name=elasticsearch state=latest update_cache=yes

- name: make sure there is a DATA directory
  file: path=/data state=directory mode=0770 owner=root group=elasticsearch

- name: copy elasticsearch environment file
  template: src=files/jvm.options dest=/etc/elasticsearch/jvm.options owner=root group=elasticsearch mode=0660

- name: copy main configuration
  copy:
   src={{elasticsearch.file.src}}
   dest=/etc/elasticsearch/elasticsearch.yml
   owner=root
   group=elasticsearch
   mode=0660

- name: run elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

